title: OpenLattice Help
email: support@openlattice.com
description: > # Welcome to OpenLattice. These are the support resources to help you use the OpenLattice platform.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: openlattice_logo.png
homepage: https://openlattice.com

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  guides:
    output: true
    permalink: /guides/:path/
    title: :title
  info:
    output: true
    permalink: /info/:path/
    title: :title
  emails:
    output: true
    permalink: /emails/:path/
